[build]
  publish = "dist"
  command = "npm run build"

[[headers]]
  for = "/service-worker.js"
  [headers.values]
    Cache-Control = "max-age=0,no-cache,no-store,must-revalidate"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200